begin;

create table if not exists public.product_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  event_name text not null,
  event_id uuid null references public.events(id) on delete set null,
  source text null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists product_events_created_at_idx
  on public.product_events (created_at);

create index if not exists product_events_event_name_created_at_idx
  on public.product_events (event_name, created_at);

create index if not exists product_events_source_created_at_idx
  on public.product_events (source, created_at);

create index if not exists product_events_user_event_created_at_idx
  on public.product_events (user_id, event_id, created_at);

alter table public.product_events enable row level security;

drop policy if exists "product_events_insert_own" on public.product_events;
create policy "product_events_insert_own"
on public.product_events
for insert
to authenticated
with check (user_id = auth.uid());

drop policy if exists "product_events_admin_read" on public.product_events;
create policy "product_events_admin_read"
on public.product_events
for select
to authenticated
using (public.is_admin());

drop policy if exists "product_events_no_client_update" on public.product_events;
create policy "product_events_no_client_update"
on public.product_events
for update
to authenticated
using (false)
with check (false);

drop policy if exists "product_events_no_client_delete" on public.product_events;
create policy "product_events_no_client_delete"
on public.product_events
for delete
to authenticated
using (false);

commit;
