begin;

-- Centralized app error sink (Sentry-equivalent fallback) for alpha operations.
create table if not exists public.app_error_logs (
  id bigint generated by default as identity primary key,
  user_id uuid null references auth.users(id) on delete set null,
  surface text not null check (surface in ('frontend', 'edge')),
  kind text not null,
  message text not null,
  stack text null,
  context jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists app_error_logs_created_at_idx
  on public.app_error_logs (created_at desc);

create index if not exists app_error_logs_surface_created_at_idx
  on public.app_error_logs (surface, created_at desc);

alter table public.app_error_logs enable row level security;

drop policy if exists "app_error_logs_admin_read" on public.app_error_logs;
create policy "app_error_logs_admin_read"
on public.app_error_logs
for select
to authenticated
using (public.is_admin());

drop policy if exists "app_error_logs_no_client_write" on public.app_error_logs;
create policy "app_error_logs_no_client_write"
on public.app_error_logs
for all
to authenticated
using (false)
with check (false);

create or replace function public.log_client_error(
  p_kind text,
  p_message text,
  p_stack text default null,
  p_context jsonb default '{}'::jsonb
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if coalesce(trim(p_kind), '') = '' or coalesce(trim(p_message), '') = '' then
    return;
  end if;

  insert into public.app_error_logs (user_id, surface, kind, message, stack, context)
  values (
    auth.uid(),
    'frontend',
    trim(p_kind),
    left(trim(p_message), 2000),
    case when p_stack is null then null else left(p_stack, 6000) end,
    coalesce(p_context, '{}'::jsonb)
  );
end;
$$;

grant execute on function public.log_client_error(text, text, text, jsonb) to anon, authenticated;

-- Reintroduce friend-add limits with alpha-friendly thresholds.
create or replace function public.tg_rate_limit_friendships_insert()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if public.is_admin() then
    return new;
  end if;

  if coalesce(auth.jwt()->>'role', '') = 'service_role' then
    return new;
  end if;

  perform public.enforce_action_rate_limit(new.user_id, 'friend_add_insert', interval '15 seconds', 4);
  return new;
end;
$$;

drop trigger if exists friendships_rate_limit_insert on public.friendships;
create trigger friendships_rate_limit_insert
before insert on public.friendships
for each row
execute function public.tg_rate_limit_friendships_insert();

-- Server-side invite creation limits (authoritative; complements client checks).
create or replace function public.tg_rate_limit_referrals_insert()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if public.is_admin() then
    return new;
  end if;

  if coalesce(auth.jwt()->>'role', '') = 'service_role' then
    return new;
  end if;

  perform public.enforce_action_rate_limit(new.inviter_user_id, 'invite_create_burst', interval '30 seconds', 6);
  perform public.enforce_action_rate_limit(new.inviter_user_id, 'invite_create_daily', interval '1 day', 80);
  return new;
end;
$$;

drop trigger if exists referrals_rate_limit_insert on public.referrals;
create trigger referrals_rate_limit_insert
before insert on public.referrals
for each row
execute function public.tg_rate_limit_referrals_insert();

commit;
